# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml make-jar
    - name: find files
      run: find .
    - name: Push jar file back to repo
      run: |
        git config --global user.email "git@github.com"
        git config --global user.name "GITHUB Action"
        git add jar
        git commit -m 'updated build from GITHUB action'
        git push
